trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerImageName: '$(docker_hub_username)/fiapcloudgames-usuarios'
  dockerfilePath: 'Dockerfile'
  azureSubscription: 'Azure'
  azureWebAppName: 'FCG-USUARIOS'
  dockerHubServiceConnection: 'DockerHubServiceConnection'

steps:
  - task: UseDotNet@2
    displayName: 'Instalar .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - task: DotNetCoreCLI@2
    displayName: 'Restaurar pacotes Nuget'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Compilar aplicação'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Executar testes'
    inputs:
      command: 'test'
      projects: '**/FCG.Tests.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'

  - script: |
      echo $(docker_hub_password) | docker login -u $(docker_hub_username) --password-stdin
    displayName: 'Login no Docker Hub via script'

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      repository: '$(dockerImageName)'
      command: 'build'
      dockerfile: $(dockerfilePath)
      tags: |
        latest

  - task: Docker@2
    displayName: 'Push Docker image para Docker Hub'
    inputs:
      repository: '$(dockerImageName)'
      command: 'push'
      tags: |
        latest

  - task: AzureWebAppContainer@1
    displayName: 'Deploy no Azure Web App'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(azureWebAppName)
      containers: |
        $(dockerImageName):latest
